name = "family-finance"
type = "javascript"
pages_build_output_dir = ".next/standalone/public"

[env.production]
name = "family-finance-prod"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "family-finance-staging"
